### ISSUE TITLE
Swag init no longer works after updating to 1.5.1

### ISSUE THREAD

**Issue by lsattem** [swaggo/swag#428]
**Describe the bug**
Previously used Swaggo/Swag 1.5.0. No longer works after updating to 1.5.1. Getting the following output:
```
2019/07/01 10:31:18 Generate swagger docs....
2019/07/01 10:31:18 Generate general API Info
2019/07/01 10:31:18 execute go list command, exit status 1
```

**To Reproduce**
Not entirely sure. Using a standard layout with cmd, pkg and internal folders. Running swag init from project root folder.

1. Use swag 1.5.1
2. Run swag init.

**Expected behavior**
Swag generates swagger docs in docs-folder.

**Your swag version**
1.5.1

**Your go version**
1.12.6

**Comment by JackDrakkar** [comment]
same thing

```bash
swag -v
swag version v1.5.1
go version
go version go1.11.10 linux/amd64
swag init -g src/main.go
2019/07/01 12:14:54 Generate swagger docs....
2019/07/01 12:14:54 Generate general API Info, search dir:./
2019/07/01 12:14:54 execute go list command, exit status 1, stdout:, stderr:can't load package: package project/backend: no Go files in /go/src/project/backend
m
```

**Comment by easonlin404** [comment]
@JackDrakkar swag will parse project's external dependencies now(using go list command). 
In your case , throwing this error message `no Go files in /go/src/project/backend` caused by your proejct has imported package/dir in `go/src/project/backend` and it doesn't a go package.

**Comment by easonlin404** [comment]
@lsattem please `go get -u github.com/swaggo/swag/cmd/swag` to get against the latest swag that will show detail error messages on console.

**Comment by lsattem** [comment]
```
2019/07/02 08:16:56 Generate swagger docs....
2019/07/02 08:16:56 Generate general API Info, search dir:./
2019/07/02 08:16:56 execute go list command, exit status 1, stdout:, stderr:can't load package: package bitbucket.org/USER/REPO: no Go files in /home/USER/go/src/bitbucket.org/USER/REPO*
```
*Where USER/REPO are user and repo details.
It seems the use of `go list` doesn't support the a project structure with pkg, internal and cmd folders, and expects all go files to be on root level. Adding a "test.go" file to project root makes Swag output the following error instead:
```
2019/07/02 08:24:40 Generate swagger docs....
2019/07/02 08:24:40 Generate general API Info, search dir:./
error:  cannot parse source files: open main.go: no such file or directory
2019/07/02 08:24:40 cannot parse source files: open main.go: no such file or directory
```

Adding a "main.go" file to project root makes it work just fine. We could add all swagger doc to this file, but this isn't a very good solution.

**Comment by easonlin404** [comment]
@lsattem The issue have fixes after merged https://github.com/swaggo/swag/pull/425. And now you update version to v1.6.0 and execute the following to specify paring outside dependencies, disabled by default.
`swag init --parseDependency=true`

**Comment by JackDrakkar** [comment]
we have almost the same project structure as @lsattem
Today I updated swag to v1.6.0, and it works fine as
```bash
swag init -d api -g main.go
```
without any changes in the project structure
I had some errors on v1.5.1 yesterday, but today I cannot reproduce them

**Comment by easonlin404** [comment]
@JackDrakkar Please update version to v1.6.0 and you can add `--parseDependency=true` flag if u want to outside dependencies.

**Comment by lsattem** [comment]
@easonlin404 I used v1.6.0 when writing the previous message. Adding --parseDependency=true does not make any difference. This is not an outside dependency, as I understand it. The swagger doc is in a file in this specific project, and Swag no longer seems able to detect any go files in my project.

Running the following:
```bash
swag --version
echo "running 'swag init -g \"$SWAGGER_INFO\"' --parseDependency=true"
swag init -g "$SWAGGER_INFO" --parseDependency=true
```

Yields this output:
```
swag version v1.6.0
running 'swag init -g "./pkg/swagger/info.go"' --parseDependency=true
2019/07/02 11:06:06 Generate swagger docs....
2019/07/02 11:06:06 Generate general API Info, search dir:./
2019/07/02 11:06:06 execute go list command, exit status 1, stdout:, stderr:can't load package: package bitbucket.org/USER/REPO: no Go files in /home/USER/go/src/bitbucket.org/USER/REPO
```

Relevant project structure
```yaml
root:
  cmd:
    main:
      - main.go # run program
  pkg:
    swagger:
      - info.go #contains general swagger info
  internal:
    api:
      - api.go #contains http end points with swagger comments

```

I tried playing around with the "-d" and "-g", parameters (e.g. full path), but to no avail. It still is unable to detect any go files.

**Comment by easonlin404** [comment]
Please ignore passing `parseDependency` flag, in your project structure you can executes the following: 
```
swag init -g cmd/main.go
``` 

or `cd` to `cmd/main` folder and try `swag init`.

**Comment by lsattem** [comment]
That works, but it does not really solve the problem for me.  If i write `swag init -g ../../pkg/swagger/info.go`  from cmd/main I get an output containing general swagger info, but my api paths are not included since they're located in ../../internal/api/api.go.

**Comment by easonlin404** [comment]
Because swag only parse go files in `main.go` folder recursively. If enable `parseDependency=true` , 
 your project's dependencies have to a valid go package via `go list`.

**Comment by lsattem** [comment]
This fixed the problem. Thank you very much! 

This setup works, with a swagger info file on root level, and calling `swag init -g swaggerinfo.go` from root. Current project structure:
```yaml
root:
  swaggerinfo.go #contains general swagger info
  cmd:
    main:
      - main.go # run program
  internal:
    api:
      - api.go #contains http end points with swagger comments

```
Swaggo/Swag should perhaps be versioned 2.0.0, instead of 1.6.0, since this requirement is a breaking change. Our setup used to work, and no longer does after upgrading from 1.5.0 to 1.5.1 and then 1.6.0. 
 As of 1.6.0 the documentation is misleading. Following the documentation and running something similar to `swag init -g http/api.go` does not work. E.g. for us writing `swag init -g pkg/swagger/info.go`. You now have to run the command from the `api.go` directory, or write `swag init -g api.go -d http`. In our case the latter snippet would be `swag init -g info.go -d pkg/swagger`. 

This solution also works, and is probably best for us to maintain package conventions:
```yaml
root:
  main.go #empty dummy go file with package declaration *
  cmd:
    main:
      - main.go # run program
  internal:
    api:
      - api.go #contains http end points with swagger comments
  pkg:
    swagger:
      info.go #contains swagger information
```
* Where root level main.go looks like this
```
package dummy
```

However, this feels very hacky. Some suggestions: 
- Could you perhaps add a new parameter that specifies the folder from which a recursive search from endpoints is made? This is what I expected the `--dir` parameter to do as of today by reading the `swag init --help`
- Or allow multiple paths for the `--dir` parameter, so you could for example say: `swag init -g info.go --dir pkg/swagger/ --dir internal/api --dir ....`
- Or maybe just the file general info not to be a .go file? I.e. calling it 'swagger.myfile' instead of 'swagger.go' and running `swag init -g swagger.myfile`? (simply to avoid having a dummy package)

**Comment by blxzfb307** [comment]
I have the same problem with swag v1.6.0
I use the go module for my project and when I execute `swag i app/main/main.go` I get the below message
```
2019/07/06 16:57:36 Generate swagger docs....
2019/07/06 16:57:36 Generate general API Info, search dir:./
2019/07/06 16:57:36 execute go list command, exit status 1, stdout:, stderr:can't load package: package <my-project-name>: unknown import path "<my-project-name>": cannot find module providing package <my-project-name>
```

**Comment by easonlin404** [comment]
@blxzfb307 could you help execute `go list` at the folder that executes swag? Because swag would recognize dependencies via `go list`.

**Comment by blxzfb307** [comment]
I actually get the same message when I execute `go list` like below
```
can't load package: package <my-project-name>: unknown import path "<my-project-name>": cannot find module providing package <my-project-name>
```
However, executing `swag i app/main/main.go` can work in previous version (v1.4.0)

**Comment by easonlin404** [comment]
sorry for responses I misled you. I would want you that executing the following:
``
go list <absolute-path-your-project>/app/main/main.go
``

**Comment by blxzfb307** [comment]
I got the message below
```
command-line-arguments
```

**Comment by easonlin404** [comment]
How about `go list <absolute-path-your-project>/app/main`?

**Comment by blxzfb307** [comment]
I got `<my-project-name>/app/main`

**Comment by easonlin404** [comment]
It's hard to reproduce. Could you please create a reproduced repo that I can help ?

**Comment by blxzfb307** [comment]
I'm sorry to keep you waiting. This is the[ reproduced repo](https://github.com/blxzfb307/swag-test).
I run ` swag init -g app/main/mian.go` and get below message
```
2019/07/06 17:56:24 Generate swagger docs....
2019/07/06 17:56:24 Generate general API Info, search dir:./
2019/07/06 17:56:24 execute go list command, exit status 1, stdout:, stderr:can't load package: package swag-test: unknown import path "swag-test": cannot find module providing package swag-test
```

**Comment by easonlin404** [comment]
@blxzfb307 Thank you, I will take a look.

**Comment by easonlin404** [comment]
Please use [v1.6.1](https://github.com/swaggo/swag/releases/tag/v1.6.1) version. Please raise a new issue if have any problems.

**Comment by dantheman213** [comment]
I'm having this exact same issue on swag v1.6.7. What was the best recommended fix? Tried everything in this thread and it doesn't work. Following project structure as recommended here:

https://github.com/golang-standards/project-layout

cmd/app/main.go <- the application entrypoint and where initial swagger attributes are above main()
pkg/api/server.go <- where the HTTP API starts up with Echo
pkg/api/<entity>/<entity>.go <- multiple folders that follow this path. Each entity contains a set of API docs for their respective API routes.

**Comment by m0xxz** [comment]
> I'm having this exact same issue on swag v1.6.7. What was the best recommended fix? Tried everything in this thread and it doesn't work. Following project structure as recommended here:
> 
> https://github.com/golang-standards/project-layout
> 
> cmd/app/main.go <- the application entrypoint and where initial swagger attributes are above main()
> pkg/api/server.go <- where the HTTP API starts up with Echo
> pkg/api/[entity]/[entity].go <- multiple folders that follow this path. Each entity contains a set of API docs for their respective API routes.

I am having the same issue, can we reopen this or get pointed to the correct solution?
