### ISSUE TITLE
Version 1.6.9 - cannot find type definition

### ISSUE THREAD

**Issue by berayb** [swaggo/swag#817]
Go version : 1.15.2 (1.15.3 gives installation error)
Swag version: 1.6.9

Error : ParseComment error in file app/services/api/v1/models.go :cannot find type definition: models.ResponseType

Import: 
import models "rest-api/app/models/api/v1"

Usage : 
// @Failure 400 {object} models.ResponseType

This works fine on version 1.6.8.

**Comment by amanessinger** [comment]
Same here: type used in `@Success` is not found.

```
package handlers

import (
	"github.com/labstack/echo/v4"
	"net/http"
)

//
// Headers godoc
// @Summary returns the HTTP headers
// @Description use this to inspect the headers set by the portal and received by the service
// @Produce json
// @Success 200 {object} http.Header
// @Router /v1/headers [get]
func (env *Env) Headers(c echo.Context) error {
	return c.JSON(http.StatusOK, c.Request().Header)
}
```

With 1.6.9, I get "_ParseComment error in file internal/handlers/headers.go :cannot find type definition: http.Header_".

If I change the annotation to

```
// @Success 200 {object} map[string][]string
```

which is the definition of `http.Header`, it works.

At the moment I've reverted to 1.6.7

**Comment by berayb** [comment]
For those who need a quick solution: 
`go get -u github.com/swaggo/swag/cmd/swag@v1.6.7    `

**Comment by psyhonut** [comment]
I'm here with same problem.
@easonlin404

**Comment by agzuniverse** [comment]
Same problem, this seems to be a pretty breaking change that also possibly conflicts with the examples in the repository currently.

Downgrading to 1.6.7 caused other issues.

**Comment by sdghchj** [comment]
@amanessinger  @agzuniverse @psyhonut 
Hi, here I explain how to use ----parseDependency.
Before you run `swag init --parseDependency main.go`, you have to import all your dependent packages in your main.go.


```
//main.go

package main

import - "rest-api/app/models/api/v1"

```

```
//api.go

import models "rest-api/app/models/api/v1"

// @failure 400 {object} models.ResponseType
func MyAPI( ) {

}
```

**Comment by sdghchj** [comment]
@amanessinger 
http.Header is a type from internal pacakge. for `net/http` is from go SDK.
So you need to add `--parseInternal` when running `swag init`

**Comment by sdghchj** [comment]
@amanessinger 
http.Header is from go SDK, so it is a internal type.
--parseInternal depends on  --parseDependency.

```
//main.go

package main

import _ "net/http"

```

```
//api.go

package API

import "net/http"

// @sucess 400 {object} http.Header
func MyAPI( ) {

}
```

You need to run:
` 
swag init --parseDependency  --parseInternal -g main.go 
`

`--parseDepth`  has been included for higher performance from v1.6.9, so you can run:
` 
swag init --parseDependency  --parseInternal --parseDepth 1  -g main.go 
`

**Comment by sdghchj** [comment]
En, the usage of --parseDependency and --parseInternal needs to be included in readme.md in future, I think.

**Comment by amanessinger** [comment]
@sdghchj 
OK, now that absolutely makes sense. Yes, documenting that usage prominently would be a good idea. Thanks for the answer.

**Comment by seven-jinxin** [comment]
> For those who need a quick solution:
> `go get -u github.com/swaggo/swag/cmd/swag@v1.6.7 `

thanks！ it works for me

**Comment by Abszissex** [comment]
@berayb 
> For those who need a quick solution:
> go get -u github.com/swaggo/swag/cmd/swag@v1.6.7

Unfortunately doesn't really work for me. 
Good thing: It compiles
Bad thing:  The swagger documentation isn't found anymore when trying to access it as before:
![image](https://user-images.githubusercontent.com/4190798/108588668-b07a7b80-735a-11eb-9134-f85056712182.png)

That is how I set up the route for the swagger documentation after hitting `swag init` 
```go
	app.Get("/swagger/*", swagger.New(swagger.Config{
		URL:         "/swagger/doc.json",
		DeepLinking: false,
	}))
```
Serves correctly with `swag@v1.7.0`

**Comment by eduardo-mior** [comment]
swag init --parseDependency --parseInternal works for my

**Comment by LowryTang** [comment]
@Abszissex  I add `--parseDepth 1` to reduce the parsing time.

**Comment by IgorHalfeld** [comment]
`swag init --parseDependency --parseInternal --parseDepth 1` worked like a charm

**Comment by rcrick** [comment]
> `swag init --parseDependency --parseInternal --parseDepth 1` worked like a charm

It work for me, thx!

**Comment by zeromsi** [comment]
swag init --parseDependency --parseInternal

**Comment by zx1986** [comment]
`swag init --parseDependency --parseInternal --parseDepth 1` not work for me :-(

golang:1.16

**Comment by lixd** [comment]
I meet the same question：

```go
// @Success      200  {object}  srv.Result{data=respmodel.AnswerItem}
```

and swag init error:

```go
cannot find type definition: respmodel.AnswerItem
```



I tried `--parseInternal depends on --parseDependency.` it does not work for me.

finally, I find the true reason, **There has some same name struct in respmodel packages**。

I changed those names， it works。

hope this has helped.

**Comment by geoherna** [comment]
> I meet the same question：
> 
> ```go
> // @Success      200  {object}  srv.Result{data=respmodel.AnswerItem}
> ```
> 
> and swag init error:
> 
> ```go
> cannot find type definition: respmodel.AnswerItem
> ```
> 
> I tried `--parseInternal depends on --parseDependency.` it does not work for me.
> 
> finally, I find the true reason, **There has some same name struct in respmodel packages**。
> 
> > such as user project has a respmodel package def an AnswerItem, and admin project has a respmodel package def an AnswerItem.And those two projects are in one repo.
> 
> I changed those names， it works。
> 
> hope this has helped.

This solved the issue for me. Thank you @lixd

**Comment by Vkutovoy92** [comment]
> @amanessinger @agzuniverse @psyhonut Hi, here I explain how to use --parseDependency. Before you run `swag init --parseDependency -g main.go`, you have to import all your dependent packages in your main.go.
> 
> ```
> //main.go
> 
> package main
> 
> import _ "rest-api/app/models/api/v1"
> ```
> 
> ```
> //api.go
> 
> package API
> 
> import models "rest-api/app/models/api/v1"
> 
> // @failure 400 {object} models.ResponseType
> func MyAPI( ) {
> 
> }
> ```

Thanks a lot!!!!
