### ISSUE TITLE
I updated to the latest version, but I can't parse the data type.

### ISSUE THREAD

**Issue by medivh-jay** [swaggo/swag#814]
**Describe the bug**

My package structure is roughly as follows

```
packages_1 
      |-----------pkg1
      |-----------pkg2
packages_2 
      |-----------pkg1
      |-----------pkg2

controllers
     .....
```

Structures with the same name under packages_1 and packages_2， such as packages_2/pkg1.User, packages_2/pkg1.User, 
My swag comments look something like this
```
// @Success 200 {object} response.Response{data=[]pkg1.User}
```

Swag will throw an error:
```
ParseComment error in file xxx.go :cannot find type definition: pkg1.User
```

Even though I import dependencies in the main package `import _ "email_a/package_2/pkg"`

**To Reproduce**
1. `go get -u github.com/swaggo/swag/cmd/swag`
2. `mkdir for-swag` and `cd for-swag`
3. `go mod init for-swag`
4. `mkdir -p cmd`
4. `touch cmd/main.go`
5. `mkdir -p package_1/pkg`
6. `mkdir -p package_1/pkg1`
7. `mkdir -p package_2/pkg`
8. `mkdir -p response`
9. Create the same structure in package_1/pkg1,package_1/pkg and package_2/pkg, such as User
```
type User struct {
	ID int
}
```
10. Create a Response structure in the response package
```
type Response struct {
	Data interface{}
}
```
11. Write the following in main.go
```
// Controller xxxx
// @Tags xxxx
// @Summary xxxx
// @Description xxxx
// @Accept  mpfd
// @Produce  json
// @Success 200 {object} response.Response{data=[]pkg1.User}
// @Success 404 {object} response.Response{data=[]pkg.User}
// @Router / [get]
func Controller()  {

}

// @title SWAG
// @version 1.0
func main()  {

}
```
12. Command `swag init --generalInfo=cmd/main.go --output=docs`

**Expected behavior**
Normal analysis
This can work in swag 1.6.7

**Screenshots**
```
├── cmd
│   └── main.go
├── go.mod
├── package_1
│   ├── pkg
│   │   └── user.go
│   └── pkg1
│       └── user.go
├── package_2
│   └── pkg
│       └── user.go
└── response
    └── response.go
```

**Your swag version**
e.g. 1.6.8    (the `swag --version` retuen a incorrect version number)

**Your go version**
e.g. 1.15.2

**Desktop (please complete the following information):**
 - OS: Manjaro amd64

**Comment by thinkgos** [comment]
I find the same bug. but it can work in swag 1.6.7

**Comment by ubogdan** [comment]
@medivh-jay Data is an interface type and it can't be translated into an actual response definition because go is not an oracle that can predict whatever you are going to assign there in the future.

**Comment by medivh-jay** [comment]
@ubogdan I know what you're talking about.  But  `/ / @Success 404 {object} response.Response{data=[]pkg.User}`  is supported by swag

**Comment by ubogdan** [comment]
@medivh-jay well I don't really have time to debug this, but you may try to return a collection of users like this
```
package response

type Users []pkg.User
```
and in the controller, you can use
```
/ / @Success 404 {object} response.Users
```

**Comment by medivh-jay** [comment]
> I find the same bug. but it can work well in swag 1.6.7

@thinkgos Actually, there's a solution. If you want to take effect on 1.6.8, the go file must exist under the root of the project.

@ubogdan Thank you very much. In fact, there is a solution to this situation, that is, a go file must be created under the root path of the project, so that an error will not be returned when swag executes go list.

**Comment by sdghchj** [comment]
> > I find the same bug. but it can work well in swag 1.6.7
> 
> @thinkgos Actually, there's a solution. If you want to take effect on 1.6.8, the go file must exist under the root of the project.
> 
> @ubogdan Thank you very much. In fact, there is a solution to this situation, that is, a go file must be created under the root path of the project, so that an error will not be returned when swag executes go list.

Yes, if there is no go files in current directory,  `go list` will fail.
The popurse of `go list` is to get the import path of current directory, on which all the sub directories' import paths are based.
