### ISSUE TITLE
Global type override in .swaggo file not working

### ISSUE THREAD

**Issue by bmpotter** [swaggo/swag#1131]
**Describe the bug**
First, thank you for this excellent swaggo project! It is a great productivity enhancement.

The `replace` statement in `.swaggo` does not seem to be honored for an external type. I can successfully use `swaggertype` for every use of that external type in all of my structs, but i want to be able to define the alternate type once in the `.swaggo` file instead.

**To Reproduce**
Use this `main.go` file:

```
package main

import (
	"fmt"
	"github.com/lib/pq"
)

type MyStruct struct {
	Foo    string         `json:"foo"`    // some field
	Labels pq.StringArray `json:"labels"` // external type not found in .swaggo file

	//Labels pq.StringArray `json:"labels" swaggertype:"array,string"` // this works
}

// @Router /myroute [get]
// @Summary Get something
// @id get
// @Tags MyStruct
// @Produce json
// @Success 200 {object} MyStruct "Resource returned"
func Get() {
	fmt.Println("getting something")
}

// @title My test case
// @version 0.1
// @tag.name MyStruct
func main() {
	fmt.Println("hello")
}
```

And use this `.swaggo` file:

```
// swag does not pick this up, still get msg: cannot find type definition: pq.StringArray
replace github.com/lib/pq.StringArray []string

// Also tried these:
// replace lib/pq.StringArray []string
// replace pq.StringArray []string
// skip github.com/lib/pq.StringArray
```

Then run `$GOPATH/bin/swag init` and you'll get this output:

```
2022/02/09 06:32:08 Using overrides from .swaggo
2022/02/09 06:32:08 Generate swagger docs....
2022/02/09 06:32:08 Generate general API Info, search dir:./
2022/02/09 06:32:08 Generating main.MyStruct
2022/02/09 06:32:08 ParseComment error in file /Users/bp/src/POCs/swaggo-file-bug/main.go :cannot find type definition: pq.StringArray
```

**Expected behavior**
It should run without error, and in the generated `docs/swagger.*` files it should define the `labels` field as a string array.

**Your swag version**
The same problem occurs in both:
v1.7.8
v1.7.9-p1

**Your go version**
1.17.5

**Desktop:**
MacOS Big Sur 11.6

**Comment by ubogdan** [comment]
Hi, this is a quite new feature and for sure it's not perfect. This is also an open-source project and everything was realized with the community contribution. 
If you find this feature useful and you have some spare time feel free to contribute and we will be more than happy to assist you with a code review.

**Comment by ubogdan** [comment]
duplicate https://github.com/swaggo/swag/issues/1208

implemented in https://github.com/swaggo/swag/pull/1209 and you will be able to benefit from it in v1.8.4.

**Comment by bmpotter** [comment]
It works in `v1.8.4`, thx! This issue can be closed.
