### ISSUE TITLE
Parsing generic type to dto: cannot find type definition T (v1.8.7)

### ISSUE THREAD

**Issue by meysamhadeli** [swaggo/swag#1354]
I have a problem with pars my response dto in generic approach:
in this example, `GetProductsResponseDto` is my generic response dto with some nested field code:
```go
package v1

import (
	uuid "github.com/satori/go.uuid"
	"time"
)

type GetProductsResponseDto struct {
	Products *ListResult[*ProductDto]
}

type ProductDto struct {
	ProductId   uuid.UUID `json:"productId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ListResult[T any] struct {
	Size       int   `json:"size,omitempty" bson:"size"`
	Page       int   `json:"page,omitempty" bson:"page"`
	TotalItems int64 `json:"totalItems,omitempty" bson:"totalItems"`
	TotalPage  int   `json:"totalPage,omitempty" bson:"totalPage"`
	Items      []T   `json:"items,omitempty" bson:"items"`
}
```

In my endpoint level I use this `// @Success 200 {object} v1.GetProductsResponseDto` for parsing swagger and I get this error `cannot find type definition: T` in CLI version ` v1.8.7`. But it works correctly with old CLI version `v1.8.3`.

Seems CLI version ` v1.8.7` has some problem with parsing some generic like this.

- Swag Version:  1.8.7
- Go Version: 1.19
- OS: Windows 11
- Browser: Chrome
- Version: 106.0.52

**Comment by sdghchj** [comment]
I have tested your code with v1.8.7 and it works alright.

**Comment by meysamhadeli** [comment]
> I have tested your code with v1.8.7 and it works alright.

Thanks. I check it again with a simple example and my code run correctly.
